#
# meson.build for the TeX Live subdirectory libs/icu/
#
# Copyright 2025-2026 Yukimasa Morimi <h20y6m@yahoo.co.jp>
# You may freely use, modify and/or distribute this file.

subdir('include/unicode')

icu_dir = '../../../libs/icu'
icu_src = icu_dir / 'icu-src/source'

icu_version = run_command(
  find_program('get-icu-version.py'),
  icu_dir / 'version.ac',
  check: true).stdout().strip()

icu_major = icu_version.split('.')[0]

icu_static = get_option('no_icu_dll')


icu_defines = [
  '-DWIN32=1',
  # Disable some warnings. ICU gives a lot of warnings.
  '/wd4244',
  '/wd4275',
  '/wd4805',
]
if icu_static
  icu_defines += ['-DU_STATIC_IMPLEMENTATION']
endif

## stubdata

if icu_static
  icu_stubdata_lib = static_library('icustubdata',
    icu_src / 'stubdata/stubdata.cpp',
    include_directories: [icu_src / 'common'],
    c_args: icu_defines,
    cpp_args: icu_defines,
  )
else
  icu_stubdata_lib = shared_library('icustubdata',
    icu_src / 'stubdata/stubdata.cpp',
    include_directories: [icu_src / 'common'],
    c_args: icu_defines,
    cpp_args: icu_defines,
  )
endif

## common

icu_common_sources = [
  icu_src / 'common/appendable.cpp',
  icu_src / 'common/bmpset.cpp',
  icu_src / 'common/brkeng.cpp',
  icu_src / 'common/brkiter.cpp',
  icu_src / 'common/bytesinkutil.cpp',
  icu_src / 'common/bytestream.cpp',
  icu_src / 'common/bytestrie.cpp',
  icu_src / 'common/bytestriebuilder.cpp',
  icu_src / 'common/bytestrieiterator.cpp',
  icu_src / 'common/caniter.cpp',
  icu_src / 'common/characterproperties.cpp',
  icu_src / 'common/chariter.cpp',
  icu_src / 'common/charstr.cpp',
  icu_src / 'common/cmemory.cpp',
  icu_src / 'common/cstr.cpp',
  icu_src / 'common/cstring.cpp',
  icu_src / 'common/cwchar.cpp',
  icu_src / 'common/dictbe.cpp',
  icu_src / 'common/dictionarydata.cpp',
  icu_src / 'common/dtintrv.cpp',
  icu_src / 'common/edits.cpp',
  icu_src / 'common/emojiprops.cpp',
  icu_src / 'common/errorcode.cpp',
  icu_src / 'common/filteredbrk.cpp',
  icu_src / 'common/filterednormalizer2.cpp',
  icu_src / 'common/fixedstring.cpp',
  icu_src / 'common/icudataver.cpp',
  icu_src / 'common/icuplug.cpp',
  icu_src / 'common/loadednormalizer2impl.cpp',
  icu_src / 'common/localebuilder.cpp',
  icu_src / 'common/localematcher.cpp',
  icu_src / 'common/localeprioritylist.cpp',
  icu_src / 'common/locavailable.cpp',
  icu_src / 'common/locbased.cpp',
  icu_src / 'common/locdispnames.cpp',
  icu_src / 'common/locdistance.cpp',
  icu_src / 'common/locdspnm.cpp',
  icu_src / 'common/locid.cpp',
  icu_src / 'common/loclikely.cpp',
  icu_src / 'common/loclikelysubtags.cpp',
  icu_src / 'common/locmap.cpp',
  icu_src / 'common/locresdata.cpp',
  icu_src / 'common/locutil.cpp',
  icu_src / 'common/lsr.cpp',
  icu_src / 'common/lstmbe.cpp',
  icu_src / 'common/messagepattern.cpp',
  icu_src / 'common/mlbe.cpp',
  icu_src / 'common/normalizer2.cpp',
  icu_src / 'common/normalizer2impl.cpp',
  icu_src / 'common/normlzr.cpp',
  icu_src / 'common/parsepos.cpp',
  icu_src / 'common/patternprops.cpp',
  icu_src / 'common/pluralmap.cpp',
  icu_src / 'common/propname.cpp',
  icu_src / 'common/propsvec.cpp',
  icu_src / 'common/punycode.cpp',
  icu_src / 'common/putil.cpp',
  icu_src / 'common/rbbi.cpp',
  icu_src / 'common/rbbi_cache.cpp',
  icu_src / 'common/rbbidata.cpp',
  icu_src / 'common/rbbinode.cpp',
  icu_src / 'common/rbbirb.cpp',
  icu_src / 'common/rbbiscan.cpp',
  icu_src / 'common/rbbisetb.cpp',
  icu_src / 'common/rbbistbl.cpp',
  icu_src / 'common/rbbitblb.cpp',
  icu_src / 'common/resbund.cpp',
  icu_src / 'common/resbund_cnv.cpp',
  icu_src / 'common/resource.cpp',
  icu_src / 'common/restrace.cpp',
  icu_src / 'common/ruleiter.cpp',
  icu_src / 'common/schriter.cpp',
  icu_src / 'common/serv.cpp',
  icu_src / 'common/servlk.cpp',
  icu_src / 'common/servlkf.cpp',
  icu_src / 'common/servls.cpp',
  icu_src / 'common/servnotf.cpp',
  icu_src / 'common/servrbf.cpp',
  icu_src / 'common/servslkf.cpp',
  icu_src / 'common/sharedobject.cpp',
  icu_src / 'common/simpleformatter.cpp',
  icu_src / 'common/static_unicode_sets.cpp',
  icu_src / 'common/stringpiece.cpp',
  icu_src / 'common/stringtriebuilder.cpp',
  icu_src / 'common/uarrsort.cpp',
  icu_src / 'common/ubidi.cpp',
  icu_src / 'common/ubidi_props.cpp',
  icu_src / 'common/ubidiln.cpp',
  icu_src / 'common/ubiditransform.cpp',
  icu_src / 'common/ubidiwrt.cpp',
  icu_src / 'common/ubrk.cpp',
  icu_src / 'common/ucase.cpp',
  icu_src / 'common/ucasemap.cpp',
  icu_src / 'common/ucasemap_titlecase_brkiter.cpp',
  icu_src / 'common/ucat.cpp',
  icu_src / 'common/uchar.cpp',
  icu_src / 'common/ucharstrie.cpp',
  icu_src / 'common/ucharstriebuilder.cpp',
  icu_src / 'common/ucharstrieiterator.cpp',
  icu_src / 'common/uchriter.cpp',
  icu_src / 'common/ucln_cmn.cpp',
  icu_src / 'common/ucmndata.cpp',
  icu_src / 'common/ucnv.cpp',
  icu_src / 'common/ucnv2022.cpp',
  icu_src / 'common/ucnv_bld.cpp',
  icu_src / 'common/ucnv_cb.cpp',
  icu_src / 'common/ucnv_cnv.cpp',
  icu_src / 'common/ucnv_ct.cpp',
  icu_src / 'common/ucnv_err.cpp',
  icu_src / 'common/ucnv_ext.cpp',
  icu_src / 'common/ucnv_io.cpp',
  icu_src / 'common/ucnv_lmb.cpp',
  icu_src / 'common/ucnv_set.cpp',
  icu_src / 'common/ucnv_u16.cpp',
  icu_src / 'common/ucnv_u32.cpp',
  icu_src / 'common/ucnv_u7.cpp',
  icu_src / 'common/ucnv_u8.cpp',
  icu_src / 'common/ucnvbocu.cpp',
  icu_src / 'common/ucnvdisp.cpp',
  icu_src / 'common/ucnvhz.cpp',
  icu_src / 'common/ucnvisci.cpp',
  icu_src / 'common/ucnvlat1.cpp',
  icu_src / 'common/ucnvmbcs.cpp',
  icu_src / 'common/ucnvscsu.cpp',
  icu_src / 'common/ucnvsel.cpp',
  icu_src / 'common/ucol_swp.cpp',
  icu_src / 'common/ucptrie.cpp',
  icu_src / 'common/ucurr.cpp',
  icu_src / 'common/udata.cpp',
  icu_src / 'common/udatamem.cpp',
  icu_src / 'common/udataswp.cpp',
  icu_src / 'common/uenum.cpp',
  icu_src / 'common/uhash.cpp',
  icu_src / 'common/uhash_us.cpp',
  icu_src / 'common/uidna.cpp',
  icu_src / 'common/uinit.cpp',
  icu_src / 'common/uinvchar.cpp',
  icu_src / 'common/uiter.cpp',
  icu_src / 'common/ulist.cpp',
  icu_src / 'common/uloc.cpp',
  icu_src / 'common/uloc_keytype.cpp',
  icu_src / 'common/uloc_tag.cpp',
  icu_src / 'common/ulocale.cpp',
  icu_src / 'common/ulocbuilder.cpp',
  icu_src / 'common/umapfile.cpp',
  icu_src / 'common/umath.cpp',
  icu_src / 'common/umutablecptrie.cpp',
  icu_src / 'common/umutex.cpp',
  icu_src / 'common/unames.cpp',
  icu_src / 'common/unifiedcache.cpp',
  icu_src / 'common/unifilt.cpp',
  icu_src / 'common/unifunct.cpp',
  icu_src / 'common/uniset.cpp',
  icu_src / 'common/uniset_closure.cpp',
  icu_src / 'common/uniset_props.cpp',
  icu_src / 'common/unisetspan.cpp',
  icu_src / 'common/unistr.cpp',
  icu_src / 'common/unistr_case.cpp',
  icu_src / 'common/unistr_case_locale.cpp',
  icu_src / 'common/unistr_cnv.cpp',
  icu_src / 'common/unistr_props.cpp',
  icu_src / 'common/unistr_titlecase_brkiter.cpp',
  icu_src / 'common/unorm.cpp',
  icu_src / 'common/unormcmp.cpp',
  icu_src / 'common/uobject.cpp',
  icu_src / 'common/uprops.cpp',
  icu_src / 'common/ures_cnv.cpp',
  icu_src / 'common/uresbund.cpp',
  icu_src / 'common/uresdata.cpp',
  icu_src / 'common/usc_impl.cpp',
  icu_src / 'common/uscript.cpp',
  icu_src / 'common/uscript_props.cpp',
  icu_src / 'common/uset.cpp',
  icu_src / 'common/uset_props.cpp',
  icu_src / 'common/usetiter.cpp',
  icu_src / 'common/ushape.cpp',
  icu_src / 'common/usprep.cpp',
  icu_src / 'common/ustack.cpp',
  icu_src / 'common/ustr_cnv.cpp',
  icu_src / 'common/ustr_titlecase_brkiter.cpp',
  icu_src / 'common/ustr_wcs.cpp',
  icu_src / 'common/ustrcase.cpp',
  icu_src / 'common/ustrcase_locale.cpp',
  icu_src / 'common/ustrenum.cpp',
  icu_src / 'common/ustrfmt.cpp',
  icu_src / 'common/ustring.cpp',
  icu_src / 'common/ustrtrns.cpp',
  icu_src / 'common/utext.cpp',
  icu_src / 'common/utf_impl.cpp',
  icu_src / 'common/util.cpp',
  icu_src / 'common/util_props.cpp',
  icu_src / 'common/utrace.cpp',
  icu_src / 'common/utrie.cpp',
  icu_src / 'common/utrie2.cpp',
  icu_src / 'common/utrie2_builder.cpp',
  icu_src / 'common/utrie_swap.cpp',
  icu_src / 'common/uts46.cpp',
  icu_src / 'common/utypes.cpp',
  icu_src / 'common/uvector.cpp',
  icu_src / 'common/uvectr32.cpp',
  icu_src / 'common/uvectr64.cpp',
  icu_src / 'common/wintz.cpp',
]

icu_common_defines = icu_defines + [
  '-DU_COMMON_IMPLEMENTATION',
]

if icu_static
  icu_common_lib = static_library('icuuc',
    icu_common_sources,
    c_args: icu_common_defines,
    cpp_args: icu_common_defines,
  )
else
  icu_common_stubdata_dll = shared_library('icuuc-stubdata',
    icu_common_sources,
    c_args : icu_common_defines,
    cpp_args : icu_common_defines,
    link_with : [
      icu_stubdata_lib,
    ],
  )
  icu_common_lib = icu_common_stubdata_dll
endif

## i18n

icu_i18n_sources = [
  icu_src / 'i18n/alphaindex.cpp',
  icu_src / 'i18n/anytrans.cpp',
  icu_src / 'i18n/astro.cpp',
  icu_src / 'i18n/basictz.cpp',
  icu_src / 'i18n/bocsu.cpp',
  icu_src / 'i18n/brktrans.cpp',
  icu_src / 'i18n/buddhcal.cpp',
  icu_src / 'i18n/calendar.cpp',
  icu_src / 'i18n/casetrn.cpp',
  icu_src / 'i18n/cecal.cpp',
  icu_src / 'i18n/chnsecal.cpp',
  icu_src / 'i18n/choicfmt.cpp',
  icu_src / 'i18n/coleitr.cpp',
  icu_src / 'i18n/coll.cpp',
  icu_src / 'i18n/collation.cpp',
  icu_src / 'i18n/collationbuilder.cpp',
  icu_src / 'i18n/collationcompare.cpp',
  icu_src / 'i18n/collationdata.cpp',
  icu_src / 'i18n/collationdatabuilder.cpp',
  icu_src / 'i18n/collationdatareader.cpp',
  icu_src / 'i18n/collationdatawriter.cpp',
  icu_src / 'i18n/collationfastlatin.cpp',
  icu_src / 'i18n/collationfastlatinbuilder.cpp',
  icu_src / 'i18n/collationfcd.cpp',
  icu_src / 'i18n/collationiterator.cpp',
  icu_src / 'i18n/collationkeys.cpp',
  icu_src / 'i18n/collationroot.cpp',
  icu_src / 'i18n/collationrootelements.cpp',
  icu_src / 'i18n/collationruleparser.cpp',
  icu_src / 'i18n/collationsets.cpp',
  icu_src / 'i18n/collationsettings.cpp',
  icu_src / 'i18n/collationtailoring.cpp',
  icu_src / 'i18n/collationweights.cpp',
  icu_src / 'i18n/compactdecimalformat.cpp',
  icu_src / 'i18n/coptccal.cpp',
  icu_src / 'i18n/cpdtrans.cpp',
  icu_src / 'i18n/csdetect.cpp',
  icu_src / 'i18n/csmatch.cpp',
  icu_src / 'i18n/csr2022.cpp',
  icu_src / 'i18n/csrecog.cpp',
  icu_src / 'i18n/csrmbcs.cpp',
  icu_src / 'i18n/csrsbcs.cpp',
  icu_src / 'i18n/csrucode.cpp',
  icu_src / 'i18n/csrutf8.cpp',
  icu_src / 'i18n/curramt.cpp',
  icu_src / 'i18n/currfmt.cpp',
  icu_src / 'i18n/currpinf.cpp',
  icu_src / 'i18n/currunit.cpp',
  icu_src / 'i18n/dangical.cpp',
  icu_src / 'i18n/datefmt.cpp',
  icu_src / 'i18n/dayperiodrules.cpp',
  icu_src / 'i18n/dcfmtsym.cpp',
  icu_src / 'i18n/decContext.cpp',
  icu_src / 'i18n/decNumber.cpp',
  icu_src / 'i18n/decimfmt.cpp',
  icu_src / 'i18n/displayoptions.cpp',
  icu_src / 'i18n/double-conversion-bignum-dtoa.cpp',
  icu_src / 'i18n/double-conversion-bignum.cpp',
  icu_src / 'i18n/double-conversion-cached-powers.cpp',
  icu_src / 'i18n/double-conversion-double-to-string.cpp',
  icu_src / 'i18n/double-conversion-fast-dtoa.cpp',
  icu_src / 'i18n/double-conversion-string-to-double.cpp',
  icu_src / 'i18n/double-conversion-strtod.cpp',
  icu_src / 'i18n/dtfmtsym.cpp',
  icu_src / 'i18n/dtitvfmt.cpp',
  icu_src / 'i18n/dtitvinf.cpp',
  icu_src / 'i18n/dtptngen.cpp',
  icu_src / 'i18n/dtrule.cpp',
  icu_src / 'i18n/erarules.cpp',
  icu_src / 'i18n/esctrn.cpp',
  icu_src / 'i18n/ethpccal.cpp',
  icu_src / 'i18n/fmtable.cpp',
  icu_src / 'i18n/fmtable_cnv.cpp',
  icu_src / 'i18n/format.cpp',
  icu_src / 'i18n/formatted_string_builder.cpp',
  icu_src / 'i18n/formattedval_iterimpl.cpp',
  icu_src / 'i18n/formattedval_sbimpl.cpp',
  icu_src / 'i18n/formattedvalue.cpp',
  icu_src / 'i18n/fphdlimp.cpp',
  icu_src / 'i18n/fpositer.cpp',
  icu_src / 'i18n/funcrepl.cpp',
  icu_src / 'i18n/gender.cpp',
  icu_src / 'i18n/gregocal.cpp',
  icu_src / 'i18n/gregoimp.cpp',
  icu_src / 'i18n/hebrwcal.cpp',
  icu_src / 'i18n/indiancal.cpp',
  icu_src / 'i18n/inputext.cpp',
  icu_src / 'i18n/islamcal.cpp',
  icu_src / 'i18n/iso8601cal.cpp',
  icu_src / 'i18n/japancal.cpp',
  icu_src / 'i18n/listformatter.cpp',
  icu_src / 'i18n/measfmt.cpp',
  icu_src / 'i18n/measunit.cpp',
  icu_src / 'i18n/measunit_extra.cpp',
  icu_src / 'i18n/measure.cpp',
  icu_src / 'i18n/msgfmt.cpp',
  icu_src / 'i18n/messageformat2.cpp',
  icu_src / 'i18n/messageformat2_arguments.cpp',
  icu_src / 'i18n/messageformat2_checker.cpp',
  icu_src / 'i18n/messageformat2_data_model.cpp',
  icu_src / 'i18n/messageformat2_errors.cpp',
  icu_src / 'i18n/messageformat2_evaluation.cpp',
  icu_src / 'i18n/messageformat2_formatter.cpp',
  icu_src / 'i18n/messageformat2_formattable.cpp',
  icu_src / 'i18n/messageformat2_function_registry.cpp',
  icu_src / 'i18n/messageformat2_parser.cpp',
  icu_src / 'i18n/messageformat2_serializer.cpp',
  icu_src / 'i18n/name2uni.cpp',
  icu_src / 'i18n/nfrs.cpp',
  icu_src / 'i18n/nfrule.cpp',
  icu_src / 'i18n/nfsubs.cpp',
  icu_src / 'i18n/nortrans.cpp',
  icu_src / 'i18n/nultrans.cpp',
  icu_src / 'i18n/number_affixutils.cpp',
  icu_src / 'i18n/number_asformat.cpp',
  icu_src / 'i18n/number_capi.cpp',
  icu_src / 'i18n/number_compact.cpp',
  icu_src / 'i18n/number_currencysymbols.cpp',
  icu_src / 'i18n/number_decimalquantity.cpp',
  icu_src / 'i18n/number_decimfmtprops.cpp',
  icu_src / 'i18n/number_fluent.cpp',
  icu_src / 'i18n/number_formatimpl.cpp',
  icu_src / 'i18n/number_grouping.cpp',
  icu_src / 'i18n/number_integerwidth.cpp',
  icu_src / 'i18n/number_longnames.cpp',
  icu_src / 'i18n/number_mapper.cpp',
  icu_src / 'i18n/number_modifiers.cpp',
  icu_src / 'i18n/number_multiplier.cpp',
  icu_src / 'i18n/number_notation.cpp',
  icu_src / 'i18n/number_output.cpp',
  icu_src / 'i18n/number_padding.cpp',
  icu_src / 'i18n/number_patternmodifier.cpp',
  icu_src / 'i18n/number_patternstring.cpp',
  icu_src / 'i18n/number_rounding.cpp',
  icu_src / 'i18n/number_scientific.cpp',
  icu_src / 'i18n/number_simple.cpp',
  icu_src / 'i18n/number_skeletons.cpp',
  icu_src / 'i18n/number_symbolswrapper.cpp',
  icu_src / 'i18n/number_usageprefs.cpp',
  icu_src / 'i18n/number_utils.cpp',
  icu_src / 'i18n/numfmt.cpp',
  icu_src / 'i18n/numparse_affixes.cpp',
  icu_src / 'i18n/numparse_compositions.cpp',
  icu_src / 'i18n/numparse_currency.cpp',
  icu_src / 'i18n/numparse_decimal.cpp',
  icu_src / 'i18n/numparse_impl.cpp',
  icu_src / 'i18n/numparse_parsednumber.cpp',
  icu_src / 'i18n/numparse_scientific.cpp',
  icu_src / 'i18n/numparse_symbols.cpp',
  icu_src / 'i18n/numparse_validators.cpp',
  icu_src / 'i18n/numrange_capi.cpp',
  icu_src / 'i18n/numrange_fluent.cpp',
  icu_src / 'i18n/numrange_impl.cpp',
  icu_src / 'i18n/numsys.cpp',
  icu_src / 'i18n/olsontz.cpp',
  icu_src / 'i18n/persncal.cpp',
  icu_src / 'i18n/pluralranges.cpp',
  icu_src / 'i18n/plurfmt.cpp',
  icu_src / 'i18n/plurrule.cpp',
  icu_src / 'i18n/quant.cpp',
  icu_src / 'i18n/quantityformatter.cpp',
  icu_src / 'i18n/rbnf.cpp',
  icu_src / 'i18n/rbt.cpp',
  icu_src / 'i18n/rbt_data.cpp',
  icu_src / 'i18n/rbt_pars.cpp',
  icu_src / 'i18n/rbt_rule.cpp',
  icu_src / 'i18n/rbt_set.cpp',
  icu_src / 'i18n/rbtz.cpp',
  icu_src / 'i18n/regexcmp.cpp',
  icu_src / 'i18n/regeximp.cpp',
  icu_src / 'i18n/regexst.cpp',
  icu_src / 'i18n/regextxt.cpp',
  icu_src / 'i18n/region.cpp',
  icu_src / 'i18n/reldatefmt.cpp',
  icu_src / 'i18n/reldtfmt.cpp',
  icu_src / 'i18n/rematch.cpp',
  icu_src / 'i18n/remtrans.cpp',
  icu_src / 'i18n/repattrn.cpp',
  icu_src / 'i18n/rulebasedcollator.cpp',
  icu_src / 'i18n/scientificnumberformatter.cpp',
  icu_src / 'i18n/scriptset.cpp',
  icu_src / 'i18n/search.cpp',
  icu_src / 'i18n/selfmt.cpp',
  icu_src / 'i18n/sharedbreakiterator.cpp',
  icu_src / 'i18n/simpletz.cpp',
  icu_src / 'i18n/smpdtfmt.cpp',
  icu_src / 'i18n/smpdtfst.cpp',
  icu_src / 'i18n/sortkey.cpp',
  icu_src / 'i18n/standardplural.cpp',
  icu_src / 'i18n/string_segment.cpp',
  icu_src / 'i18n/strmatch.cpp',
  icu_src / 'i18n/strrepl.cpp',
  icu_src / 'i18n/stsearch.cpp',
  icu_src / 'i18n/taiwncal.cpp',
  icu_src / 'i18n/timezone.cpp',
  icu_src / 'i18n/titletrn.cpp',
  icu_src / 'i18n/tmunit.cpp',
  icu_src / 'i18n/tmutamt.cpp',
  icu_src / 'i18n/tmutfmt.cpp',
  icu_src / 'i18n/tolowtrn.cpp',
  icu_src / 'i18n/toupptrn.cpp',
  icu_src / 'i18n/translit.cpp',
  icu_src / 'i18n/transreg.cpp',
  icu_src / 'i18n/tridpars.cpp',
  icu_src / 'i18n/tzfmt.cpp',
  icu_src / 'i18n/tzgnames.cpp',
  icu_src / 'i18n/tznames.cpp',
  icu_src / 'i18n/tznames_impl.cpp',
  icu_src / 'i18n/tzrule.cpp',
  icu_src / 'i18n/tztrans.cpp',
  icu_src / 'i18n/ucal.cpp',
  icu_src / 'i18n/ucln_in.cpp',
  icu_src / 'i18n/ucol.cpp',
  icu_src / 'i18n/ucol_res.cpp',
  icu_src / 'i18n/ucol_sit.cpp',
  icu_src / 'i18n/ucoleitr.cpp',
  icu_src / 'i18n/ucsdet.cpp',
  icu_src / 'i18n/udat.cpp',
  icu_src / 'i18n/udateintervalformat.cpp',
  icu_src / 'i18n/udatpg.cpp',
  icu_src / 'i18n/ufieldpositer.cpp',
  icu_src / 'i18n/uitercollationiterator.cpp',
  icu_src / 'i18n/ulistformatter.cpp',
  icu_src / 'i18n/ulocdata.cpp',
  icu_src / 'i18n/umsg.cpp',
  icu_src / 'i18n/unesctrn.cpp',
  icu_src / 'i18n/uni2name.cpp',
  icu_src / 'i18n/units_data.cpp',
  icu_src / 'i18n/units_complexconverter.cpp',
  icu_src / 'i18n/units_converter.cpp',
  icu_src / 'i18n/units_router.cpp',
  icu_src / 'i18n/unum.cpp',
  icu_src / 'i18n/unumsys.cpp',
  icu_src / 'i18n/upluralrules.cpp',
  icu_src / 'i18n/uregex.cpp',
  icu_src / 'i18n/uregexc.cpp',
  icu_src / 'i18n/uregion.cpp',
  icu_src / 'i18n/usearch.cpp',
  icu_src / 'i18n/uspoof.cpp',
  icu_src / 'i18n/uspoof_build.cpp',
  icu_src / 'i18n/uspoof_conf.cpp',
  icu_src / 'i18n/uspoof_impl.cpp',
  icu_src / 'i18n/utf16collationiterator.cpp',
  icu_src / 'i18n/utf8collationiterator.cpp',
  icu_src / 'i18n/utmscale.cpp',
  icu_src / 'i18n/utrans.cpp',
  icu_src / 'i18n/vtzone.cpp',
  icu_src / 'i18n/vzone.cpp',
  icu_src / 'i18n/windtfmt.cpp',
  icu_src / 'i18n/winnmfmt.cpp',
  icu_src / 'i18n/wintzimpl.cpp',
  icu_src / 'i18n/zonemeta.cpp',
  icu_src / 'i18n/zrule.cpp',
  icu_src / 'i18n/ztrans.cpp',
]

icu_i18n_defines = icu_defines + [
  '-DU_I18N_IMPLEMENTATION',
]

if icu_static
  icu_i18n_lib = static_library('icui18n',
    icu_i18n_sources,
    include_directories: [icu_src / 'common'],
    c_args: icu_i18n_defines,
    cpp_args: icu_i18n_defines,
  )
else
  icu_i18n_stubdata_dll = shared_library('icui18n-stubdata',
    icu_i18n_sources,
    include_directories: [icu_src / 'common'],
    c_args: icu_i18n_defines,
    cpp_args: icu_i18n_defines,
    link_with : [
      icu_common_lib,
    ],
    version : icu_version,
  )
  icu_i18n_lib = icu_i18n_stubdata_dll
endif

## tools/toolutil

icu_toolutil_sources = [
  icu_src / 'tools/toolutil/collationinfo.cpp',
  icu_src / 'tools/toolutil/dbgutil.cpp',
  icu_src / 'tools/toolutil/denseranges.cpp',
  icu_src / 'tools/toolutil/filestrm.cpp',
  icu_src / 'tools/toolutil/filetools.cpp',
  icu_src / 'tools/toolutil/flagparser.cpp',
  icu_src / 'tools/toolutil/package.cpp',
  icu_src / 'tools/toolutil/pkg_genc.cpp',
  icu_src / 'tools/toolutil/pkg_gencmn.cpp',
  icu_src / 'tools/toolutil/pkg_icu.cpp',
  icu_src / 'tools/toolutil/pkgitems.cpp',
  icu_src / 'tools/toolutil/ppucd.cpp',
  icu_src / 'tools/toolutil/swapimpl.cpp',
  icu_src / 'tools/toolutil/toolutil.cpp',
  icu_src / 'tools/toolutil/ucbuf.cpp',
  icu_src / 'tools/toolutil/ucln_tu.cpp',
  icu_src / 'tools/toolutil/ucm.cpp',
  icu_src / 'tools/toolutil/ucmstate.cpp',
  icu_src / 'tools/toolutil/udbgutil.cpp',
  icu_src / 'tools/toolutil/unewdata.cpp',
  icu_src / 'tools/toolutil/uoptions.cpp',
  icu_src / 'tools/toolutil/uparse.cpp',
  icu_src / 'tools/toolutil/writesrc.cpp',
  icu_src / 'tools/toolutil/xmlparser.cpp',
]

icu_toolutil_defines = icu_defines + [
  '-DU_TOOLUTIL_IMPLEMENTATION',
]

if icu_static
  icu_toolutil_lib = static_library('icutu',
    icu_toolutil_sources,
    include_directories: [
      icu_src / 'common',
      icu_src / 'i18n',
    ],
    c_args: icu_toolutil_defines,
    cpp_args: icu_toolutil_defines,
  )
else
  icu_toolutil_stubdata_dll = shared_library('icutu-stubdata',
    icu_toolutil_sources,
    include_directories: [
      icu_src / 'common',
      icu_src / 'i18n',
    ],
    c_args: icu_toolutil_defines,
    cpp_args: icu_toolutil_defines,
    link_with : [
      icu_i18n_lib,
      icu_common_lib,
    ],
  )
  icu_toolutil_lib = icu_toolutil_stubdata_dll
endif

## tools/icupkg

icu_icupkg_exe = executable('icupkg',
  icu_src / 'tools/icupkg/icupkg.cpp',
  include_directories : [
    icu_src / 'common',
    icu_src / 'tools/toolutil',
  ],
  cpp_args : icu_defines,
  link_with : [
    icu_toolutil_lib,
    icu_i18n_lib,
    icu_common_lib,
    icu_stubdata_lib,
  ],
)

## tools/pkgdata

icu_pkgdata_exe = executable('pkgdata',
  icu_src / 'tools/pkgdata/pkgdata.cpp',
  icu_src / 'tools/pkgdata/pkgtypes.c',
  include_directories : [
    icu_src / 'common',
    icu_src / 'tools/toolutil',
  ],
  c_args : icu_defines,
  cpp_args : icu_defines,
  link_with : [
    icu_toolutil_lib,
    icu_i18n_lib,
    icu_common_lib,
    icu_stubdata_lib,
  ],
)

## packagedata

if host_machine.cpu_family() == 'aarch64'
  icu_packagedata_arch = 'ARM64'
elif host_machine.cpu_family() == 'arm'
  icu_packagedata_arch = 'ARM'
elif host_machine.cpu_family() == 'x86_64'
  icu_packagedata_arch = 'X64'
elif host_machine.cpu_family() == 'x86'
  icu_packagedata_arch = 'X86'
else
  error('Unsupported cpu_family.', host_machine.cpu_family())
endif

if icu_static
  icu_packagedata = custom_target('packagedata',
    input : [
      icu_src / f'data/in/icudt@icu_major@l.dat',
    ],
    output : [
      'icudt.lib',
    ],
    command : [
      find_program('makedata.py'),
      '--workdir', '@PRIVATE_DIR@',
      '--outdir', '@OUTDIR@',
      '--icupkg', icu_icupkg_exe,
      '--pkgdata', icu_pkgdata_exe,
      '--arch', icu_packagedata_arch,
      '--mode', 'static',
      '--version', icu_major,
      '@INPUT@',
    ],
  )
else
  icu_packagedata = custom_target('packagedata',
    input : [
      icu_src / f'data/in/icudt@icu_major@l.dat',
    ],
    output : [
      'icudt.lib',
      f'icudt@icu_major@.dll',
    ],
    command : [
      find_program('makedata.py'),
      '--workdir', '@PRIVATE_DIR@',
      '--outdir', '@OUTDIR@',
      '--icupkg', icu_icupkg_exe,
      '--pkgdata', icu_pkgdata_exe,
      '--arch', icu_packagedata_arch,
      '--mode', 'dll',
      '--version', icu_major,
      '@INPUT@',
    ],
    install : true,
    install_dir : [false, get_option('bindir')],
  )
endif

## rebuild DLL with non-stub data

if not icu_static
  icu_common_dll = shared_library('icuuc',
    objects: icu_common_stubdata_dll.extract_all_objects(recursive : false), # reuse built objects
    link_with : [
      icu_packagedata[0],
    ],
    version : icu_version,
    install : true,
  )
  icu_i18n_dll = shared_library('icui18n',
    objects: icu_i18n_stubdata_dll.extract_all_objects(recursive : false), # reuse built objects
    link_with : [
      icu_common_dll,
      icu_packagedata[0],
    ],
    version : icu_version,
    install : true,
  )
endif


## declare_dependency

if icu_static
  icu_dep = declare_dependency(
    sources: [
      icu_public_headers,
      icu_packagedata,
    ],
    include_directories: include_directories(
      'include',
    ),
    compile_args: ['-DU_STATIC_IMPLEMENTATION'],
    link_with: [
      icu_common_lib,
      icu_i18n_lib,
      icu_packagedata,
    ],
  )
else
  icu_dep = declare_dependency(
    sources: [
      icu_public_headers,
    ],
    include_directories: include_directories(
      'include',
    ),
    compile_args: [],
    link_with: [
      icu_common_dll,
      icu_i18n_dll,
    ],
  )
endif
