#
# meson.build for the TeX Live subdirectory libs/gmp/native
#
# Copyright 2025-2026 Yukimasa Morimi <h20y6m@yahoo.co.jp>
# You may freely use, modify and/or distribute this file.

gmp_native_gen_bases_exe = executable('gmp-native-gen-bases',
  '..' / gmp_tree / 'gen-bases.c',
  c_args : ['/wd4146']
)

gmp_native_gen_fac_exe = executable('gmp-native-gen-fac',
  '..' / gmp_tree / 'gen-fac.c',
  c_args : ['/wd4146']
)

gmp_native_gen_fib_exe = executable('gmp-native-gen-fib',
  '..' / gmp_tree / 'gen-fib.c',
  c_args : ['/wd4146']
)
