#
# meson.build for the TeX Live subdirectory libs/icu/include/unicode/
#
# Copyright 2025      Yukimasa Morimi <h20y6m@yahoo.co.jp>
# You may freely use, modify and/or distribute this file.

icu_dir = '../../../../../libs/icu'
icu_src = icu_dir / 'icu-src/source'

icu_public_headers = []

hdr_links = []

hdr_links += [
  icu_src / 'common/unicode/appendable.h',
  icu_src / 'common/unicode/brkiter.h',
  icu_src / 'common/unicode/bytestream.h',
  icu_src / 'common/unicode/bytestrie.h',
  icu_src / 'common/unicode/bytestriebuilder.h',
  icu_src / 'common/unicode/caniter.h',
  icu_src / 'common/unicode/casemap.h',
  icu_src / 'common/unicode/char16ptr.h',
  icu_src / 'common/unicode/chariter.h',
  icu_src / 'common/unicode/dbbi.h',
  icu_src / 'common/unicode/docmain.h',
  icu_src / 'common/unicode/dtintrv.h',
  icu_src / 'common/unicode/edits.h',
  icu_src / 'common/unicode/enumset.h',
  icu_src / 'common/unicode/errorcode.h',
  icu_src / 'common/unicode/filteredbrk.h',
  icu_src / 'common/unicode/icudataver.h',
  icu_src / 'common/unicode/icuplug.h',
  icu_src / 'common/unicode/idna.h',
  icu_src / 'common/unicode/localebuilder.h',
  icu_src / 'common/unicode/localematcher.h',
  icu_src / 'common/unicode/localpointer.h',
  icu_src / 'common/unicode/locdspnm.h',
  icu_src / 'common/unicode/locid.h',
  icu_src / 'common/unicode/messagepattern.h',
  icu_src / 'common/unicode/normalizer2.h',
  icu_src / 'common/unicode/normlzr.h',
  icu_src / 'common/unicode/parseerr.h',
  icu_src / 'common/unicode/parsepos.h',
  icu_src / 'common/unicode/platform.h',
  icu_src / 'common/unicode/ptypes.h',
  icu_src / 'common/unicode/putil.h',
  icu_src / 'common/unicode/rbbi.h',
  icu_src / 'common/unicode/rep.h',
  icu_src / 'common/unicode/resbund.h',
  icu_src / 'common/unicode/schriter.h',
  icu_src / 'common/unicode/simpleformatter.h',
  icu_src / 'common/unicode/std_string.h',
  icu_src / 'common/unicode/strenum.h',
  icu_src / 'common/unicode/stringoptions.h',
  icu_src / 'common/unicode/stringpiece.h',
  icu_src / 'common/unicode/stringtriebuilder.h',
  icu_src / 'common/unicode/symtable.h',
  icu_src / 'common/unicode/ubidi.h',
  icu_src / 'common/unicode/ubiditransform.h',
  icu_src / 'common/unicode/ubrk.h',
  icu_src / 'common/unicode/ucasemap.h',
  icu_src / 'common/unicode/ucat.h',
  icu_src / 'common/unicode/uchar.h',
  icu_src / 'common/unicode/ucharstrie.h',
  icu_src / 'common/unicode/ucharstriebuilder.h',
  icu_src / 'common/unicode/uchriter.h',
  icu_src / 'common/unicode/uclean.h',
  icu_src / 'common/unicode/ucnv.h',
  icu_src / 'common/unicode/ucnvsel.h',
  icu_src / 'common/unicode/ucnv_cb.h',
  icu_src / 'common/unicode/ucnv_err.h',
  icu_src / 'common/unicode/uconfig.h',
  icu_src / 'common/unicode/ucpmap.h',
  icu_src / 'common/unicode/ucptrie.h',
  icu_src / 'common/unicode/ucurr.h',
  icu_src / 'common/unicode/udata.h',
  icu_src / 'common/unicode/udisplaycontext.h',
  icu_src / 'common/unicode/uenum.h',
  icu_src / 'common/unicode/uidna.h',
  icu_src / 'common/unicode/uiter.h',
  icu_src / 'common/unicode/uldnames.h',
  icu_src / 'common/unicode/uloc.h',
  icu_src / 'common/unicode/ulocale.h',
  icu_src / 'common/unicode/ulocbuilder.h',
  icu_src / 'common/unicode/umachine.h',
  icu_src / 'common/unicode/umisc.h',
  icu_src / 'common/unicode/umutablecptrie.h',
  icu_src / 'common/unicode/unifilt.h',
  icu_src / 'common/unicode/unifunct.h',
  icu_src / 'common/unicode/unimatch.h',
  icu_src / 'common/unicode/uniset.h',
  icu_src / 'common/unicode/unistr.h',
  icu_src / 'common/unicode/unorm.h',
  icu_src / 'common/unicode/unorm2.h',
  icu_src / 'common/unicode/uobject.h',
  icu_src / 'common/unicode/urename.h',
  icu_src / 'common/unicode/urep.h',
  icu_src / 'common/unicode/ures.h',
  icu_src / 'common/unicode/uscript.h',
  icu_src / 'common/unicode/uset.h',
  icu_src / 'common/unicode/usetiter.h',
  icu_src / 'common/unicode/ushape.h',
  icu_src / 'common/unicode/usprep.h',
  icu_src / 'common/unicode/ustring.h',
  icu_src / 'common/unicode/ustringtrie.h',
  icu_src / 'common/unicode/utext.h',
  icu_src / 'common/unicode/utf.h',
  icu_src / 'common/unicode/utf16.h',
  icu_src / 'common/unicode/utf32.h',
  icu_src / 'common/unicode/utf8.h',
  icu_src / 'common/unicode/utf_old.h',
  icu_src / 'common/unicode/utrace.h',
  icu_src / 'common/unicode/utypes.h',
  icu_src / 'common/unicode/uvernum.h',
  icu_src / 'common/unicode/uversion.h',

  icu_src / 'i18n/unicode/alphaindex.h',
  icu_src / 'i18n/unicode/basictz.h',
  icu_src / 'i18n/unicode/calendar.h',
  icu_src / 'i18n/unicode/choicfmt.h',
  icu_src / 'i18n/unicode/coleitr.h',
  icu_src / 'i18n/unicode/coll.h',
  icu_src / 'i18n/unicode/compactdecimalformat.h',
  icu_src / 'i18n/unicode/curramt.h',
  icu_src / 'i18n/unicode/currpinf.h',
  icu_src / 'i18n/unicode/currunit.h',
  icu_src / 'i18n/unicode/datefmt.h',
  icu_src / 'i18n/unicode/dcfmtsym.h',
  icu_src / 'i18n/unicode/decimfmt.h',
  icu_src / 'i18n/unicode/displayoptions.h',
  icu_src / 'i18n/unicode/dtfmtsym.h',
  icu_src / 'i18n/unicode/dtitvfmt.h',
  icu_src / 'i18n/unicode/dtitvinf.h',
  icu_src / 'i18n/unicode/dtptngen.h',
  icu_src / 'i18n/unicode/dtrule.h',
  icu_src / 'i18n/unicode/fieldpos.h',
  icu_src / 'i18n/unicode/fmtable.h',
  icu_src / 'i18n/unicode/format.h',
  icu_src / 'i18n/unicode/formattednumber.h',
  icu_src / 'i18n/unicode/formattedvalue.h',
  icu_src / 'i18n/unicode/fpositer.h',
  icu_src / 'i18n/unicode/gender.h',
  icu_src / 'i18n/unicode/gregocal.h',
  icu_src / 'i18n/unicode/listformatter.h',
  icu_src / 'i18n/unicode/measfmt.h',
  icu_src / 'i18n/unicode/measunit.h',
  icu_src / 'i18n/unicode/measure.h',
  icu_src / 'i18n/unicode/msgfmt.h',
  icu_src / 'i18n/unicode/nounit.h',
  icu_src / 'i18n/unicode/numberformatter.h',
  icu_src / 'i18n/unicode/numberrangeformatter.h',
  icu_src / 'i18n/unicode/numfmt.h',
  icu_src / 'i18n/unicode/numsys.h',
  icu_src / 'i18n/unicode/plurfmt.h',
  icu_src / 'i18n/unicode/plurrule.h',
  icu_src / 'i18n/unicode/rbnf.h',
  icu_src / 'i18n/unicode/rbtz.h',
  icu_src / 'i18n/unicode/regex.h',
  icu_src / 'i18n/unicode/region.h',
  icu_src / 'i18n/unicode/reldatefmt.h',
  icu_src / 'i18n/unicode/scientificnumberformatter.h',
  icu_src / 'i18n/unicode/search.h',
  icu_src / 'i18n/unicode/selfmt.h',
  icu_src / 'i18n/unicode/simplenumberformatter.h',
  icu_src / 'i18n/unicode/simpletz.h',
  icu_src / 'i18n/unicode/smpdtfmt.h',
  icu_src / 'i18n/unicode/sortkey.h',
  icu_src / 'i18n/unicode/stsearch.h',
  icu_src / 'i18n/unicode/tblcoll.h',
  icu_src / 'i18n/unicode/timezone.h',
  icu_src / 'i18n/unicode/tmunit.h',
  icu_src / 'i18n/unicode/tmutamt.h',
  icu_src / 'i18n/unicode/tmutfmt.h',
  icu_src / 'i18n/unicode/translit.h',
  icu_src / 'i18n/unicode/tzfmt.h',
  icu_src / 'i18n/unicode/tznames.h',
  icu_src / 'i18n/unicode/tzrule.h',
  icu_src / 'i18n/unicode/tztrans.h',
  icu_src / 'i18n/unicode/ucal.h',
  icu_src / 'i18n/unicode/ucol.h',
  icu_src / 'i18n/unicode/ucoleitr.h',
  icu_src / 'i18n/unicode/ucsdet.h',
  icu_src / 'i18n/unicode/udat.h',
  icu_src / 'i18n/unicode/udateintervalformat.h',
  icu_src / 'i18n/unicode/udatpg.h',
  icu_src / 'i18n/unicode/udisplayoptions.h',
  icu_src / 'i18n/unicode/ufieldpositer.h',
  icu_src / 'i18n/unicode/uformattable.h',
  icu_src / 'i18n/unicode/uformattednumber.h',
  icu_src / 'i18n/unicode/uformattedvalue.h',
  icu_src / 'i18n/unicode/ugender.h',
  icu_src / 'i18n/unicode/ulistformatter.h',
  icu_src / 'i18n/unicode/ulocdata.h',
  icu_src / 'i18n/unicode/umsg.h',
  icu_src / 'i18n/unicode/unirepl.h',
  icu_src / 'i18n/unicode/unum.h',
  icu_src / 'i18n/unicode/unumberformatter.h',
  icu_src / 'i18n/unicode/unumberoptions.h',
  icu_src / 'i18n/unicode/unumberrangeformatter.h',
  icu_src / 'i18n/unicode/unumsys.h',
  icu_src / 'i18n/unicode/upluralrules.h',
  icu_src / 'i18n/unicode/uregex.h',
  icu_src / 'i18n/unicode/uregion.h',
  icu_src / 'i18n/unicode/ureldatefmt.h',
  icu_src / 'i18n/unicode/usearch.h',
  icu_src / 'i18n/unicode/usimplenumberformatter.h',
  icu_src / 'i18n/unicode/uspoof.h',
  icu_src / 'i18n/unicode/utmscale.h',
  icu_src / 'i18n/unicode/utrans.h',
  icu_src / 'i18n/unicode/vtzone.h',

  icu_src / 'io/unicode/ustdio.h',
  icu_src / 'io/unicode/ustream.h',
]

foreach hdr : hdr_links
  icu_public_headers += configure_file(
    input: hdr,
    output: fs.name(hdr),
    copy: true,
  )
endforeach
