%% for npLaTeX
%% original: uplatex.ini (written by Tono san (modified by texjporg 2016/05/12))
%%
\begingroup  \catcode`\{=1  \catcode`\}=2%
  \immediate\write20{<<< making "nplatex with Babel" format >>>}
\endgroup
\scrollmode
\ifdefined\cjkxcode
  \cjkxcode\jis"214B=4 % "）" (dummy)
  \cjkxcode\jis"3441=4 % "漢" (dummy)
\fi
\let\dump\relax
\input uplatex.ltx

\ExplSyntaxOn
\prop_gput:Nnn \g__str_alias_prop { default } {  }
    \cs_set:Npn \__str_filter_bytes:n #1
      {
        \__str_filter_bytes_aux:N #1
          { ? \prg_break: }
        \prg_break_point:
      }
    \cs_set:Npn \__str_filter_bytes_aux:N #1
      {
        \use_none:n #1
        \if_int_compare:w `#1 < 256 \exp_stop_f:
          #1
        \else:
          \flag_raise:n { str_byte }
        \fi:
        \__str_filter_bytes_aux:N
      }
    \cs_set_protected:Npn \__str_convert_unescape_:
      {
        \flag_clear:n { str_byte }
        \__kernel_tl_gset:Nx \g__str_result_tl
          { \exp_args:No \__str_filter_bytes:n \g__str_result_tl }
        \__str_if_flag_error:nnx { str_byte } { non-byte } { bytes }
      }
    \cs_set_protected:Npn \__str_convert_encode_:
      { \__str_convert_gmap_internal:N \__str_encode_native_char:n }
    \msg_set:nnnn { str } { non-byte }
      { String~invalid~in~escaping~'#1':~it~may~only~contain~bytes. }
      {
        Some~characters~in~the~string~you~asked~to~convert~are~not~
        8-bit~characters.~Perhaps~the~string~is~a~'native'~Unicode~string?~
        If~it~is,~try~using\\
        \\
        \iow_indent:n
          {
            \iow_char:N\\str_set_convert:Nnnn \\
            \ \ <str~var>~\{~<string>~\}~\{~native~\}~\{~<target~encoding>~\}
          }
      }
    \cs_set:Npn \__str_encode_native_char:n #1
      { \char_generate:nn {#1} {12} }
    \cs_set:Npn \__str_convert_pdfname:n #1
      {
        \int_compare:nNnTF { `#1 } > { "7F }
          { \__str_convert_pdfname_bytes:n {#1} }
          { \__str_escape_name_char:n {#1} }
      }
    \cs_set:Npn \__str_convert_pdfname_bytes:n #1
      {
        \exp_args:Ne \__str_convert_pdfname_bytes_aux:n
          { \__kernel_codepoint_to_bytes:n {`#1} }
      }
    \cs_set:Npn \__str_convert_pdfname_bytes_aux:n #1
      { \__str_convert_pdfname_bytes_aux:nnnn #1 }
    \cs_set:Npx \__str_convert_pdfname_bytes_aux:nnnn #1#2#3#4
      {
        \c_hash_str \exp_not:N \__str_output_hexadecimal:n {#1}
        \c_hash_str \exp_not:N \__str_output_hexadecimal:n {#2}
        \exp_not:N \tl_if_blank:nF {#3}
          {
            \c_hash_str \exp_not:N \__str_output_hexadecimal:n {#3}
            \exp_not:N \tl_if_blank:nF {#4}
              {
                \c_hash_str \exp_not:N \__str_output_hexadecimal:n {#4}
              }
          }
      }
    \cs_set:Npn \codepoint_str_generate:n #1
      {
        \int_compare:nNnTF {#1} = { `\  }
          { ~ }
          { \char_generate:nn {#1} { 12 } }
      }
   \cs_set:Npn \codepoint_generate:nn #1#2
      {
        \int_compare:nNnTF {#1} = { `\  }
          { ~ }
          {
            \__kernel_exp_not:w \exp_after:wN \exp_after:wN \exp_after:wN
              { \char_generate:nn {#1} {#2} }
          }
      }
    \cs_set:Npn \__text_codepoint_process:nN #1#2 { #1 {#2} }
    \prg_set_conditional:Npnn
      \__text_codepoint_compare:nNn #1#2#3 { TF , p }
      {
        \int_compare:nNnTF {`#1} #2 {#3}
          \prg_return_true: \prg_return_false:
      }
    \cs_set:Npn \__text_codepoint_from_chars:Nw #1 {`#1}
    \cs_set:Npn \__text_change_case_catcode:nn #1#2
      { \__text_char_catcode:N #1 }
\ExplSyntaxOff
\primitive\dump
\endinput
