#
# meson.build for the TeX Live subdirectory texk/dvipdfm-x/
#
# Copyright 2025      Yukimasa Morimi <h20y6m@yahoo.co.jp>
# You may freely use, modify and/or distribute this file.

dvipdfmx_srcdir = '../../../texk/dvipdfm-x'

dvipdfmx_version = run_command(
    find_program('get-dvipdfmx-version.py'), dvipdfmx_srcdir / 'configure.ac',
    check: true).stdout().strip()


dvipdfmx_gen_headers = []

dvipdfmx_gen_headers += configure_file(
  input : 'config.h.in',
  output : 'config.h',
  configuration : {
    'VERSION' : dvipdfmx_version,
  }
)


dvipdfmx_includes = include_directories(
  dvipdfmx_srcdir,
)

dvipdfmx_defines = [
  '-DWIN32=1',
  '-DW32TEX=1',
  '-DKPATHSEA=1',
  '-DHAVE_CONFIG_H=1',
  '-D_CRT_NONSTDC_NO_DEPRECATE',
  '-D_CRT_SECURE_NO_DEPRECATE',
]


dvipdfmx_sources = [
  dvipdfmx_srcdir / 'agl.c',
  dvipdfmx_srcdir / 'agl.h',
  dvipdfmx_srcdir / 'bmpimage.c',
  dvipdfmx_srcdir / 'bmpimage.h',
  dvipdfmx_srcdir / 'cff.c',
  dvipdfmx_srcdir / 'cff.h',
  dvipdfmx_srcdir / 'cff_dict.c',
  dvipdfmx_srcdir / 'cff_dict.h',
  dvipdfmx_srcdir / 'cff_limits.h',
  dvipdfmx_srcdir / 'cff_stdstr.h',
  dvipdfmx_srcdir / 'cff_types.h',
  dvipdfmx_srcdir / 'cid_basefont.h',
  dvipdfmx_srcdir / 'cid.c',
  dvipdfmx_srcdir / 'cid.h',
  dvipdfmx_srcdir / 'cidtype0.c',
  dvipdfmx_srcdir / 'cidtype0.h',
  dvipdfmx_srcdir / 'cidtype2.c',
  dvipdfmx_srcdir / 'cidtype2.h',
  dvipdfmx_srcdir / 'cmap.c',
  dvipdfmx_srcdir / 'cmap.h',
  dvipdfmx_srcdir / 'cmap_p.h',
  dvipdfmx_srcdir / 'cmap_read.c',
  dvipdfmx_srcdir / 'cmap_read.h',
  dvipdfmx_srcdir / 'cmap_write.c',
  dvipdfmx_srcdir / 'cmap_write.h',
  dvipdfmx_srcdir / 'cs_type2.c',
  dvipdfmx_srcdir / 'cs_type2.h',
  dvipdfmx_srcdir / 'dpxconf.c',
  dvipdfmx_srcdir / 'dpxconf.h',
  dvipdfmx_srcdir / 'dpxcrypt.c',
  dvipdfmx_srcdir / 'dpxcrypt.h',
  dvipdfmx_srcdir / 'dpxfile.c',
  dvipdfmx_srcdir / 'dpxfile.h',
  dvipdfmx_srcdir / 'dpxutil.c',
  dvipdfmx_srcdir / 'dpxutil.h',
  dvipdfmx_srcdir / 'dvi.c',
  dvipdfmx_srcdir / 'dvi.h',
  dvipdfmx_srcdir / 'dvicodes.h',
  dvipdfmx_srcdir / 'dvipdfmx.c',
  dvipdfmx_srcdir / 'dvipdfmx.h',
  dvipdfmx_srcdir / 'epdf.c',
  dvipdfmx_srcdir / 'epdf.h',
  dvipdfmx_srcdir / 'error.c',
  dvipdfmx_srcdir / 'error.h',
  dvipdfmx_srcdir / 'fontmap.c',
  dvipdfmx_srcdir / 'fontmap.h',
  dvipdfmx_srcdir / 'jp2image.c',
  dvipdfmx_srcdir / 'jp2image.h',
  dvipdfmx_srcdir / 'jpegimage.c',
  dvipdfmx_srcdir / 'jpegimage.h',
  dvipdfmx_srcdir / 'mem.c',
  dvipdfmx_srcdir / 'mem.h',
  dvipdfmx_srcdir / 'mfileio.c',
  dvipdfmx_srcdir / 'mfileio.h',
  dvipdfmx_srcdir / 'mpost.c',
  dvipdfmx_srcdir / 'mpost.h',
  dvipdfmx_srcdir / 'mt19937ar.c',
  dvipdfmx_srcdir / 'numbers.c',
  dvipdfmx_srcdir / 'numbers.h',
  dvipdfmx_srcdir / 'otl_opt.c',
  dvipdfmx_srcdir / 'otl_opt.h',
  dvipdfmx_srcdir / 'pdfcolor.c',
  dvipdfmx_srcdir / 'pdfcolor.h',
  dvipdfmx_srcdir / 'pdfdev.c',
  dvipdfmx_srcdir / 'pdfdev.h',
  dvipdfmx_srcdir / 'pdfdoc.c',
  dvipdfmx_srcdir / 'pdfdoc.h',
  dvipdfmx_srcdir / 'pdfdraw.c',
  dvipdfmx_srcdir / 'pdfdraw.h',
  dvipdfmx_srcdir / 'pdfencrypt.c',
  dvipdfmx_srcdir / 'pdfencrypt.h',
  dvipdfmx_srcdir / 'pdfencoding.c',
  dvipdfmx_srcdir / 'pdfencoding.h',
  dvipdfmx_srcdir / 'pdffont.c',
  dvipdfmx_srcdir / 'pdffont.h',
  dvipdfmx_srcdir / 'pdflimits.h',
  dvipdfmx_srcdir / 'pdfnames.c',
  dvipdfmx_srcdir / 'pdfnames.h',
  dvipdfmx_srcdir / 'pdfobj.c',
  dvipdfmx_srcdir / 'pdfobj.h',
  dvipdfmx_srcdir / 'pdfparse.c',
  dvipdfmx_srcdir / 'pdfparse.h',
  dvipdfmx_srcdir / 'pdfresource.c',
  dvipdfmx_srcdir / 'pdfresource.h',
  dvipdfmx_srcdir / 'pdfximage.c',
  dvipdfmx_srcdir / 'pdfximage.h',
  dvipdfmx_srcdir / 'pkfont.c',
  dvipdfmx_srcdir / 'pkfont.h',
  dvipdfmx_srcdir / 'pngimage.c',
  dvipdfmx_srcdir / 'pngimage.h',
  dvipdfmx_srcdir / 'pst.c',
  dvipdfmx_srcdir / 'pst.h',
  dvipdfmx_srcdir / 'pst_obj.c',
  dvipdfmx_srcdir / 'pst_obj.h',
  dvipdfmx_srcdir / 'sfnt.c',
  dvipdfmx_srcdir / 'sfnt.h',
  dvipdfmx_srcdir / 'spc_color.c',
  dvipdfmx_srcdir / 'spc_color.h',
  dvipdfmx_srcdir / 'spc_dvipdfmx.c',
  dvipdfmx_srcdir / 'spc_dvipdfmx.h',
  dvipdfmx_srcdir / 'spc_dvips.c',
  dvipdfmx_srcdir / 'spc_dvips.h',
  dvipdfmx_srcdir / 'spc_html.c',
  dvipdfmx_srcdir / 'spc_html.h',
  dvipdfmx_srcdir / 'spc_misc.c',
  dvipdfmx_srcdir / 'spc_misc.h',
  dvipdfmx_srcdir / 'spc_pdfm.c',
  dvipdfmx_srcdir / 'spc_pdfm.h',
  dvipdfmx_srcdir / 'spc_tpic.c',
  dvipdfmx_srcdir / 'spc_tpic.h',
  dvipdfmx_srcdir / 'spc_util.h',
  dvipdfmx_srcdir / 'spc_util.c',
  dvipdfmx_srcdir / 'spc_xtx.c',
  dvipdfmx_srcdir / 'spc_xtx.h',
  dvipdfmx_srcdir / 'specials.c',
  dvipdfmx_srcdir / 'specials.h',
  dvipdfmx_srcdir / 'subfont.c',
  dvipdfmx_srcdir / 'subfont.h',
  dvipdfmx_srcdir / 'system.h',
  dvipdfmx_srcdir / 't1_char.c',
  dvipdfmx_srcdir / 't1_char.h',
  dvipdfmx_srcdir / 't1_load.c',
  dvipdfmx_srcdir / 't1_load.h',
  dvipdfmx_srcdir / 'tfm.c',
  dvipdfmx_srcdir / 'tfm.h',
  dvipdfmx_srcdir / 'truetype.c',
  dvipdfmx_srcdir / 'truetype.h',
  dvipdfmx_srcdir / 'tt_aux.c',
  dvipdfmx_srcdir / 'tt_aux.h',
  dvipdfmx_srcdir / 'tt_cmap.c',
  dvipdfmx_srcdir / 'tt_cmap.h',
  dvipdfmx_srcdir / 'tt_glyf.c',
  dvipdfmx_srcdir / 'tt_glyf.h',
  dvipdfmx_srcdir / 'tt_gsub.c',
  dvipdfmx_srcdir / 'tt_gsub.h',
  dvipdfmx_srcdir / 'tt_post.c',
  dvipdfmx_srcdir / 'tt_post.h',
  dvipdfmx_srcdir / 'tt_table.c',
  dvipdfmx_srcdir / 'tt_table.h',
  dvipdfmx_srcdir / 'type0.c',
  dvipdfmx_srcdir / 'type0.h',
  dvipdfmx_srcdir / 'type1.c',
  dvipdfmx_srcdir / 'type1.h',
  dvipdfmx_srcdir / 'type1c.c',
  dvipdfmx_srcdir / 'type1c.h',
  dvipdfmx_srcdir / 'unicode.c',
  dvipdfmx_srcdir / 'unicode.h',
  dvipdfmx_srcdir / 'vf.c',
  dvipdfmx_srcdir / 'vf.h',
  dvipdfmx_srcdir / 'xbb.c',
]


dvipdfmx_dll = shared_library('dvipdfmx',
  dvipdfmx_sources,
  dvipdfmx_gen_headers,
  c_args : dvipdfmx_defines,
  include_directories : dvipdfmx_includes,
  dependencies : [
    kpathsea_dep,
    libpaper_dep,
    libpng_dep,
  ],
  install : true,
)

call_dvipdfmx_exe = executable('call-dvipdfmx',
  '../calldll/calldll.c',
  c_args : '-DDLLPROC=dlldvipdfmxmain',
  link_with: dvipdfmx_dll,
)

foreach exe : ['xdvipdfmx.exe', 'dvipdfmx.exe', 'dvipdfm.exe']
  custom_target(exe,
    input: call_dvipdfmx_exe,
    output: exe,
    command: [copyfile_py, '@INPUT@', '@OUTPUT@'],
    build_by_default : true,
    install : true,
    install_dir : get_option('bindir'),
  )
endforeach
