#
# meson.build for the TeX Live subdirectory libs/mpfr/
#
# Copyright 2026      Yukimasa Morimi <h20y6m@yahoo.co.jp>
# You may freely use, modify and/or distribute this file.

mpfr_srcdir = '../../../libs/mpfr'
mpfr_tree = mpfr_srcdir / 'mpfr-src'


mpfr_gen_headers = []

mpfr_gen_headers += configure_file(
  input : 'mparam.h.in',
  output : 'mparam.h',
  copy : true,
)


mpfr_includes = include_directories(
  mpfr_tree / 'src',
)


mpfr_defines = [
  '-DHAVE_LITTLE_ENDIAN'
]

mpfr_defines += [
  # Disable the warning because mpfr does something nasty by applying
  # the unary minus operator to unsigned integers.
  '/wd4146',
]


mpfr_sources = [
  mpfr_tree / 'src/abort_prec_max.c',
  mpfr_tree / 'src/acos.c',
  mpfr_tree / 'src/acosh.c',
  mpfr_tree / 'src/acosu.c',
  mpfr_tree / 'src/add.c',
  mpfr_tree / 'src/add1.c',
  mpfr_tree / 'src/add1sp.c',
  mpfr_tree / 'src/add_d.c',
  mpfr_tree / 'src/add_ui.c',
  mpfr_tree / 'src/agm.c',
  mpfr_tree / 'src/ai.c',
  mpfr_tree / 'src/asin.c',
  mpfr_tree / 'src/asinh.c',
  mpfr_tree / 'src/asinu.c',
  mpfr_tree / 'src/atan.c',
  mpfr_tree / 'src/atan2.c',
  mpfr_tree / 'src/atan2u.c',
  mpfr_tree / 'src/atanh.c',
  mpfr_tree / 'src/atanu.c',
  mpfr_tree / 'src/bernoulli.c',
  mpfr_tree / 'src/beta.c',
  mpfr_tree / 'src/buildopt.c',
  mpfr_tree / 'src/cache.c',
  mpfr_tree / 'src/cbrt.c',
  mpfr_tree / 'src/check.c',
  mpfr_tree / 'src/clear.c',
  mpfr_tree / 'src/clears.c',
  mpfr_tree / 'src/cmp.c',
  mpfr_tree / 'src/cmp2.c',
  mpfr_tree / 'src/cmp_d.c',
  mpfr_tree / 'src/cmp_ld.c',
  mpfr_tree / 'src/cmp_si.c',
  mpfr_tree / 'src/cmp_ui.c',
  mpfr_tree / 'src/cmpabs.c',
  mpfr_tree / 'src/cmpabs_ui.c',
  mpfr_tree / 'src/comparisons.c',
  mpfr_tree / 'src/compound.c',
  mpfr_tree / 'src/const_catalan.c',
  mpfr_tree / 'src/const_euler.c',
  mpfr_tree / 'src/const_log2.c',
  mpfr_tree / 'src/const_pi.c',
  mpfr_tree / 'src/constant.c',
  mpfr_tree / 'src/copysign.c',
  mpfr_tree / 'src/cos.c',
  mpfr_tree / 'src/cosh.c',
  mpfr_tree / 'src/cosu.c',
  mpfr_tree / 'src/cot.c',
  mpfr_tree / 'src/coth.c',
  mpfr_tree / 'src/csc.c',
  mpfr_tree / 'src/csch.c',
  mpfr_tree / 'src/d_div.c',
  mpfr_tree / 'src/d_sub.c',
  mpfr_tree / 'src/digamma.c',
  mpfr_tree / 'src/dim.c',
  mpfr_tree / 'src/div.c',
  mpfr_tree / 'src/div_2exp.c',
  mpfr_tree / 'src/div_2si.c',
  mpfr_tree / 'src/div_2ui.c',
  mpfr_tree / 'src/div_d.c',
  mpfr_tree / 'src/div_ui.c',
  mpfr_tree / 'src/dot.c',
  mpfr_tree / 'src/dump.c',
  mpfr_tree / 'src/eint.c',
  mpfr_tree / 'src/eq.c',
  mpfr_tree / 'src/erandom.c',
  mpfr_tree / 'src/erf.c',
  mpfr_tree / 'src/erfc.c',
  mpfr_tree / 'src/exceptions.c',
  mpfr_tree / 'src/exp.c',
  mpfr_tree / 'src/exp10.c',
  mpfr_tree / 'src/exp10m1.c',
  mpfr_tree / 'src/exp2.c',
  mpfr_tree / 'src/exp2m1.c',
  mpfr_tree / 'src/exp3.c',
  mpfr_tree / 'src/exp_2.c',
  mpfr_tree / 'src/expm1.c',
  mpfr_tree / 'src/extract.c',
  mpfr_tree / 'src/factorial.c',
  mpfr_tree / 'src/fits_intmax.c',
  mpfr_tree / 'src/fits_s.h',
  mpfr_tree / 'src/fits_sint.c',
  mpfr_tree / 'src/fits_slong.c',
  mpfr_tree / 'src/fits_sshort.c',
  mpfr_tree / 'src/fits_u.h',
  mpfr_tree / 'src/fits_uint.c',
  mpfr_tree / 'src/fits_uintmax.c',
  mpfr_tree / 'src/fits_ulong.c',
  mpfr_tree / 'src/fits_ushort.c',
  mpfr_tree / 'src/fma.c',
  mpfr_tree / 'src/fmma.c',
  mpfr_tree / 'src/fmod_ui.c',
  mpfr_tree / 'src/fms.c',
  mpfr_tree / 'src/fpif.c',
  mpfr_tree / 'src/frac.c',
  mpfr_tree / 'src/free_cache.c',
  mpfr_tree / 'src/frexp.c',
  mpfr_tree / 'src/gamma.c',
  mpfr_tree / 'src/gamma_inc.c',
  mpfr_tree / 'src/gammaonethird.c',
  mpfr_tree / 'src/gen_inverse.h',
  mpfr_tree / 'src/get_d.c',
  mpfr_tree / 'src/get_d128.c',
  mpfr_tree / 'src/get_d64.c',
  mpfr_tree / 'src/get_exp.c',
  mpfr_tree / 'src/get_f.c',
  mpfr_tree / 'src/get_float128.c',
  mpfr_tree / 'src/get_flt.c',
  mpfr_tree / 'src/get_ld.c',
  mpfr_tree / 'src/get_q.c',
  mpfr_tree / 'src/get_si.c',
  mpfr_tree / 'src/get_sj.c',
  mpfr_tree / 'src/get_str.c',
  mpfr_tree / 'src/get_ui.c',
  mpfr_tree / 'src/get_uj.c',
  mpfr_tree / 'src/get_z.c',
  mpfr_tree / 'src/get_z_2exp.c',
  mpfr_tree / 'src/gmp_op.c',
  mpfr_tree / 'src/grandom.c',
  mpfr_tree / 'src/hypot.c',
  mpfr_tree / 'src/ieee_floats.h',
  mpfr_tree / 'src/init.c',
  mpfr_tree / 'src/init2.c',
  mpfr_tree / 'src/inits.c',
  mpfr_tree / 'src/inits2.c',
  mpfr_tree / 'src/inp_str.c',
  mpfr_tree / 'src/int_ceil_log2.c',
  mpfr_tree / 'src/invert_limb.h',
  mpfr_tree / 'src/invsqrt_limb.h',
  mpfr_tree / 'src/isinf.c',
  mpfr_tree / 'src/isinteger.c',
  mpfr_tree / 'src/isnan.c',
  mpfr_tree / 'src/isnum.c',
  mpfr_tree / 'src/isqrt.c',
  mpfr_tree / 'src/isregular.c',
  mpfr_tree / 'src/iszero.c',
  mpfr_tree / 'src/jn.c',
  mpfr_tree / 'src/li2.c',
  mpfr_tree / 'src/lngamma.c',
  mpfr_tree / 'src/log.c',
  mpfr_tree / 'src/log10.c',
  mpfr_tree / 'src/log10p1.c',
  mpfr_tree / 'src/log1p.c',
  mpfr_tree / 'src/log2.c',
  mpfr_tree / 'src/log2p1.c',
  mpfr_tree / 'src/log_ui.c',
  mpfr_tree / 'src/logging.c',
  mpfr_tree / 'src/min_prec.c',
  mpfr_tree / 'src/minmax.c',
  mpfr_tree / 'src/modf.c',
  mpfr_tree / 'src/mp_clz_tab.c',
  mpfr_tree / 'src/mpf2mpfr.h',
  mpfr_tree / 'src/mpfr-cvers.h',
  mpfr_tree / 'src/mpfr-gmp.c',
  mpfr_tree / 'src/mpfr-gmp.h',
  mpfr_tree / 'src/mpfr-impl.h',
  mpfr_tree / 'src/mpfr-intmax.h',
  mpfr_tree / 'src/mpfr-longlong.h',
  mpfr_tree / 'src/mpfr-mini-gmp.c',
  mpfr_tree / 'src/mpfr-mini-gmp.h',
  mpfr_tree / 'src/mpfr-sassert.h',
  mpfr_tree / 'src/mpfr-thread.h',
  mpfr_tree / 'src/mpfr.h',
  mpfr_tree / 'src/mpn_exp.c',
  mpfr_tree / 'src/mul.c',
  mpfr_tree / 'src/mul_2exp.c',
  mpfr_tree / 'src/mul_2si.c',
  mpfr_tree / 'src/mul_2ui.c',
  mpfr_tree / 'src/mul_d.c',
  mpfr_tree / 'src/mul_ui.c',
  mpfr_tree / 'src/mulders.c',
  mpfr_tree / 'src/nbits_ulong.c',
  mpfr_tree / 'src/neg.c',
  mpfr_tree / 'src/next.c',
  mpfr_tree / 'src/nrandom.c',
  mpfr_tree / 'src/odd_p.c',
  mpfr_tree / 'src/out_str.c',
  mpfr_tree / 'src/pool.c',
  mpfr_tree / 'src/pow.c',
  mpfr_tree / 'src/pow_si.c',
  mpfr_tree / 'src/pow_sj.c',
  mpfr_tree / 'src/pow_ui.c',
  mpfr_tree / 'src/pow_uj.c',
  mpfr_tree / 'src/pow_z.c',
  mpfr_tree / 'src/powerof2.c',
  mpfr_tree / 'src/powr.c',
  mpfr_tree / 'src/print_raw.c',
  mpfr_tree / 'src/print_rnd_mode.c',
  mpfr_tree / 'src/printf.c',
  mpfr_tree / 'src/random_deviate.c',
  mpfr_tree / 'src/random_deviate.h',
  mpfr_tree / 'src/rec_sqrt.c',
  mpfr_tree / 'src/reldiff.c',
  mpfr_tree / 'src/rem1.c',
  mpfr_tree / 'src/rint.c',
  mpfr_tree / 'src/rndna.c',
  mpfr_tree / 'src/root.c',
  mpfr_tree / 'src/round_near_x.c',
  mpfr_tree / 'src/round_p.c',
  mpfr_tree / 'src/round_prec.c',
  mpfr_tree / 'src/scale2.c',
  mpfr_tree / 'src/sec.c',
  mpfr_tree / 'src/sech.c',
  mpfr_tree / 'src/set.c',
  mpfr_tree / 'src/set_d.c',
  mpfr_tree / 'src/set_d128.c',
  mpfr_tree / 'src/set_d64.c',
  mpfr_tree / 'src/set_dfl_prec.c',
  mpfr_tree / 'src/set_exp.c',
  mpfr_tree / 'src/set_f.c',
  mpfr_tree / 'src/set_float128.c',
  mpfr_tree / 'src/set_flt.c',
  mpfr_tree / 'src/set_inf.c',
  mpfr_tree / 'src/set_ld.c',
  mpfr_tree / 'src/set_nan.c',
  mpfr_tree / 'src/set_prc_raw.c',
  mpfr_tree / 'src/set_prec.c',
  mpfr_tree / 'src/set_q.c',
  mpfr_tree / 'src/set_rnd.c',
  mpfr_tree / 'src/set_si.c',
  mpfr_tree / 'src/set_si_2exp.c',
  mpfr_tree / 'src/set_sj.c',
  mpfr_tree / 'src/set_str.c',
  mpfr_tree / 'src/set_str_raw.c',
  mpfr_tree / 'src/set_ui.c',
  mpfr_tree / 'src/set_ui_2exp.c',
  mpfr_tree / 'src/set_uj.c',
  mpfr_tree / 'src/set_z.c',
  mpfr_tree / 'src/set_z_2exp.c',
  mpfr_tree / 'src/set_zero.c',
  mpfr_tree / 'src/setmax.c',
  mpfr_tree / 'src/setmin.c',
  mpfr_tree / 'src/setsign.c',
  mpfr_tree / 'src/sgn.c',
  mpfr_tree / 'src/si_op.c',
  mpfr_tree / 'src/signbit.c',
  mpfr_tree / 'src/sin.c',
  mpfr_tree / 'src/sin_cos.c',
  mpfr_tree / 'src/sinh.c',
  mpfr_tree / 'src/sinh_cosh.c',
  mpfr_tree / 'src/sinu.c',
  mpfr_tree / 'src/sqr.c',
  mpfr_tree / 'src/sqrt.c',
  mpfr_tree / 'src/sqrt_ui.c',
  mpfr_tree / 'src/stack_interface.c',
  mpfr_tree / 'src/strtofr.c',
  mpfr_tree / 'src/sub.c',
  mpfr_tree / 'src/sub1.c',
  mpfr_tree / 'src/sub1sp.c',
  mpfr_tree / 'src/sub_d.c',
  mpfr_tree / 'src/sub_ui.c',
  mpfr_tree / 'src/subnormal.c',
  mpfr_tree / 'src/sum.c',
  mpfr_tree / 'src/swap.c',
  mpfr_tree / 'src/tan.c',
  mpfr_tree / 'src/tanh.c',
  mpfr_tree / 'src/tanu.c',
  mpfr_tree / 'src/total_order.c',
  mpfr_tree / 'src/ubf.c',
  mpfr_tree / 'src/uceil_exp2.c',
  mpfr_tree / 'src/uceil_log2.c',
  mpfr_tree / 'src/ufloor_log2.c',
  mpfr_tree / 'src/ui_div.c',
  mpfr_tree / 'src/ui_pow.c',
  mpfr_tree / 'src/ui_pow_ui.c',
  mpfr_tree / 'src/ui_sub.c',
  mpfr_tree / 'src/urandom.c',
  mpfr_tree / 'src/urandomb.c',
  mpfr_tree / 'src/vasprintf.c',
  mpfr_tree / 'src/version.c',
  mpfr_tree / 'src/volatile.c',
  mpfr_tree / 'src/yn.c',
  mpfr_tree / 'src/zeta.c',
  mpfr_tree / 'src/zeta_ui.c',
]


mpfr_lib = static_library('mpfr',
  mpfr_sources,
  mpfr_gen_headers,
  c_args : mpfr_defines,
  cpp_args : mpfr_defines,
  include_directories : mpfr_includes,
  dependencies : [
    gmp_dep,
  ],
)


subdir('include')

mpfr_dep = declare_dependency(
  sources : mpfr_include_headers,
  include_directories : include_directories('include'),
  link_with : mpfr_lib,
  dependencies : [
    gmp_dep,
  ],
)
