name: build-windows

on:
  push:
    branches:
      - 'build-windows/*'
    tags:
      - 'build-windows/*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86-windows-msvc
            runner: windows-latest
            msvc_arch: x86
          - target: x64-windows-msvc
            runner: windows-latest
            msvc_arch: x64
          - target: arm64-windows-msvc
            runner: windows-11-arm
            msvc_arch: arm64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Meson and Ninja
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja

      - name: Set up MSVC
        shell: pwsh
        run: |
          # Setup MSVC Environment Variables
          $arch = "${{ matrix.msvc_arch }}"
          $vsversion = ""

          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          # Write-Host "::notice::vswhere = [$vswhere]"

          if (-not (Test-Path $vswhere)) {
            Write-Error "vswhere.exe not found"
            exit 1
          }

          if ("$vsversion" -ne "") {
            $vspath = & $vswhere -version $vsversion -products * -requires Microsoft.Component.MSBuild -property installationPath
          } else {
            $vspath = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          }
          # Write-Host "::notice::vspath = [$vspath]"

          if (-not (Test-Path $vspath)) {
            if ("$vsversion" -ne "") {
              Write-Error "Visual Studio $vsversion not found"
            } else {
              Write-Error "Visual Studio not found"
            }
            exit 1
          }

          $vcvars = Join-Path $vspath "VC\Auxiliary\Build\vcvarsall.bat"
          # Write-Host "::notice::vcvars = [$vcvars]"

          if (-not (Test-Path $vcvars)) {
            Write-Error "vcvarsall.bat not found"
            exit 1
          }

          Write-Host "Found with vswhere: $vcvars"

          # Save environment variables before running vcvarsall.bat
          $before = @{}
          cmd /c "SET" | ForEach-Object {
            if ($_ -match "^(.*?)=(.*)$") {
              $before[$matches[1]] = $matches[2]
            }
          }

          # Run vcvarsall.bat and capture environment variables
          $after = cmd /c "`"$vcvars`" $arch >NUL && SET"

          # vcvarsall.bat should set "INCLUDE"
          if (-not ($after -match "^INCLUDE=")) {
            Write-Error "vcvarsall.bat failed"
            exit 1
          }

          Write-Host "::group::Environment variables"

          # Set the added or modified environment variables
          $after | ForEach-Object {
            if ($_ -match "^(.*?)=(.*)$") {
              $key = $matches[1]
              $val = $matches[2]
              if (-not $before.ContainsKey($key) -or $before[$key] -ne $val) {
                Write-Host "Setting $key"
                "$key=$val" >> $env:GITHUB_ENV
              }
            }
          }

          Write-Host "::endgroup::"

          Write-Host "Configured Developer Command Prompt"

      - name: Configure (Meson)
        run: |
          meson setup --backend=ninja --buildtype=release Work-${{ matrix.target }} build-windows

      - name: Build
        run: |
          meson compile -C Work-${{ matrix.target }}

      - name: Install (staging)
        run: |
          meson install -C Work-${{ matrix.target }} --destdir ../inst-${{ matrix.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: texlive-bin-${{ matrix.target }}
          path: inst-${{ matrix.target }}/bin/*

  release:
    if: startsWith(github.ref, 'refs/tags/build-windows/')
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: Work-download
          pattern: texlive-bin-*

      - name: Zip artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path Work-zipped | Out-Null

          Get-ChildItem Work-download -Directory | ForEach-Object {
              $artifactName = $_.Name
              $sourceDir    = $_.FullName
              $zipPath      = "Work-zipped/$artifactName.zip"

              Write-Host "Creating $zipPath ..."

              Compress-Archive `
                  -Path "$sourceDir\*" `
                  -DestinationPath $zipPath `
                  -Force
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          files: |
            Work-zipped/texlive-bin-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
